### ISSUE TITLE
Update Hello_There.js

### ISSUE THREAD

**Issue by annakimdev** [ClJarvis/Hello_There#11]
In Create Hello_There.js file, "Hello World!" is console logged. It should be changed to "Hello There!".
This is my first issue and I'm participating in Hacktoberfest with Virtual Coffee. Please assign to me :)
Thank you!

**Comment by ClJarvis** [comment]
Great catch! It's yours.

**Comment by annakimdev** [comment]
Thank you! I opened a PR.
