### ISSUE TITLE
Add Hello There in Ruby

### ISSUE THREAD

**Issue by ClJarvis** [ClJarvis/Hello_There#2]
Add the `Ruby` code that would display Hello There! on screen. 

Follow the instructions on [Contribute file](https://github.com/ClJarvis/Hello_There/blob/main/Contribute.md) to add a Ruby version of "Hello There!".

Once assigned. 
* Fork this repository.
* Clone the forked repository to your machine.
* Create a new branch titles Hello_There.extenesion, with the extension being the language you are adding. (EX Hello_There.py)
* Write the code for `Hello There!` in the chosen language.
* Add a comment with a link to documentation.
* Push the code and open a pull request.
* Link to the issue in your Pull Request. (see Linked Issue below)

**Comment by gervanna** [comment]
Hello, 

Can I work on this please?

**Comment by ClJarvis** [comment]
It's yours.
