### ISSUE TITLE
Add Hello There with PHP

### ISSUE THREAD

**Issue by ClJarvis** [ClJarvis/Hello_There#3]
Add the `PHP` code that would display Hello There! on screen. 

Follow the instructions on [Contribute file](https://github.com/ClJarvis/Hello_There/blob/main/Contribute.md) to add a PHP version of "Hello There!".

Once assigned. 
* Fork this repository.
* Clone the forked repository to your machine.
* Create a new branch titles Hello_There.extenesion, with the extension being the language you are adding. (EX Hello_There.php)
* Write the code for `Hello There!` in the chosen language.
* Add a comment with a link to documentation.
* Push the code and open a pull request.

**Comment by pedaars** [comment]
I can do this
