### ISSUE TITLE
Add Hello There with C

### ISSUE THREAD

**Issue by ridonky** [ClJarvis/Hello_There#7]
Add the C code that would display Hello There! on screen.

Following instructions in #6

**Comment by ridonky** [comment]
LMK if this is a feature you'd want!

(obligatory this is my first hacktoberfest/ foray into open source)

**Comment by ClJarvis** [comment]
It's yours. Just follow the guidelines for the other issues.  Include some documentation, I don't know C, plus it'll help others.

I'm offline this weekend so won't be able to check github/email.

**Comment by Dnyanesh-Bachhav** [comment]
Hey, I have added Hello_There.c... please check it...
![HacktoberFest 2022 Submission-2](https://user-images.githubusercontent.com/81134841/194635456-d3d8fe26-ccfc-44ba-b07b-ce902920a6e6.png)

**Comment by ridonky** [comment]
Hi there, see below for Hello There in C! 

#9
